# Gradle performance improvements
org.gradle.jvmargs=-Xmx8192M
org.gradle.vfs.watch=true
kapt.use.worker.api=true
kapt.include.compile.classpath=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.warning.mode=all

loader_version=0.16.7
# Mod Properties
mod_version=0.19
maven_group=gaucho-matrero.altoclef
archives_base_name=altoclef
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.12.101-hotspot
