package adris.altoclef.tasks.speedrun.testrun2;

import adris.altoclef.tasks.speedrun.testrun2.util.GameFiles;
import adris.altoclef.tasks.speedrun.testrun2.util.RunLog;

import java.util.ArrayDeque;

/**
 * Structured fault line. Chat stays one code; the file has the playbook.
 *
 * Grep {@code altoclef/faults.log} for FAULT.
 */
public final class T2Fault {

    public static final String FILE = "faults.log";
    private static final ArrayDeque<String> LAST = new ArrayDeque<>();
    private static String lastCode = "";
    private static long lastMs;

    private T2Fault() {}

    public static void record(String code, String evidence) {
        long now = System.currentTimeMillis();
        if (code.equals(lastCode) && now - lastMs < 4000) return;
        lastCode = code;
        lastMs = now;
        String line = SpeedrunClock.now() + " " + code + " | " + evidence + " | " + hint(code);
        LAST.addLast(line);
        while (LAST.size() > 12) LAST.removeFirst();
        GameFiles.append(FILE, "FAULT " + line);
        adris.altoclef.tasks.speedrun.testrun2.fault.FaultBook.record(code, evidence, now);
        RunLog.line("FAULT " + line);
    }

    public static String recent() {
        if (LAST.isEmpty()) return "(no faults this session)";
        StringBuilder sb = new StringBuilder();
        for (String s : LAST) {
            if (sb.length() > 0) sb.append(" ;; ");
            sb.append(s);
        }
        return sb.toString();
    }

    public static String hint(String code) {
        if (code == null) return "unknown";
        return switch (code) {
            case "E10", "E102", "S102" -> "water still: swim+jump, do not pillar";
            case "E100", "S100" -> "jump-in-place: release jump, turn 90, walk. check cobble reserve";
            case "E98" -> "same XZ: ignore if Y changing (mining). else cancel path";
            case "E104", "S104" -> "GUI open: close screen before pathing";
            case "E105", "S105" -> "lava bucket and no water: get water BEFORE construct, do not swap child";
            case "E103", "S103" -> "starving: eat overlay, do not replace portal child";
            case "E108", "S108" -> "crafting table under feet: walk off, do not jump-place";
            case "E110", "S110" -> "piglin and no gold helm: equip gold or leave range";
            case "E111", "S111" -> "null portal child: parent must keep Construct sticky";
            case "E50" -> "death: @back after respawn; read last_death.txt";
            case "E60", "E119" -> "portal ignored: stand in portal block, do not rebuild";
            case "C210" -> "fell in hole: walk, do not spend reserved cobble";
            case "C211" -> "gather stale 45s: wander then retry catalogue";
            case "E116" -> "hole loop: stop place, surface bail";
            case "E133" -> "pillar ping-pong: long ban armed at this column, walk away before re-pillaring";
            case "S139" -> "rise confirmed: real escape, cool armed";
            case "S141" -> "hop not sustained: +2y with collar still closed, keep holding";
            case "S142" -> "shaft ban lifted: 1x1 shaft cannot clear a ban by walking, so pillaring is the only way out";
            case "S143" -> "wood task latched: hold the SAME child instance so it survives the reuse check";
            case "E134" -> "wood latch expired: tree unreachable — blacklist column, retarget nearest any-type log";
            case "S144" -> "S100 nudge ineffective on a collector: child replaced with TimeoutWanderTask to break the re-path loop";
            case "S145" -> "boxed with no place blocks: mining a shaft wall to get cobblestone so the S130 pillar can arm";
            case "S146" -> "iron target locked for this phase: a per-tick recompute made the count a moving target and restarted the collection";
            case "S147" -> "sticky column ban: S130 refused at a column that already ping-ponged. Repeated re-arms here mean the bot is not actually leaving the shaft.";
            case "S148" -> "sticky column ban lifted - the bot genuinely left the column.";
            case "S149" -> "blaze search latched: nether() rebuilds CollectBlazeRodsTask every tick and SearchChunksExploreTask swaps itself for a wander, so stick() must hold the live one instead of restarting the fortress search.";
            case "S150" -> "blaze search latch released - rods satisfied or phase changed.";
            case "S151" -> "surface-bail air-pocket fallback: no sky-lit air was reachable, so the bot searched for any standable air pocket (cave, tunnel, ledge) to stand in and mine out from. Repeated S151 means the bot is buried or has fallen into a hole it cannot climb out of.";
            case "S152" -> "session preserved across an interruption. onStop() used to clear sessionLive on every task swap, so an interruption re-ran onStart() and re-derived the phase from the inventory. A long fall (MLG clutch) or a respawn could restart a completed run from BOOTSTRAP.";
            case "S153" -> "kit flag kept on resume. onStart() set hadKit=true in the PORTAL resume branch, then the unconditional hadKit=false a few lines later wiped it.";
            case "S154" -> "MLG clutch chain stayed inactive: the bot is falling but has no water bucket or clutch item, so hijacking the user task could not save it and only restarted the run. Check why the bot fell and whether buckets were lost.";
            case "S155" -> "mob defense disengaged: chasing 'annoying' hostiles returns priority 65/80, which outranks the run task (50) and suspends it entirely, so no telemetry is emitted either. The engagement exceeded its time budget or the target drifted out of range, so priority was handed back for a cooldown. Repeated S155 means mobs keep spawning near the route; check whether the run is being farmed by an unlit cave.";
            case "S156" -> "surface-bail timed out: the task can only finish by reaching sky light >= 13 at y >= 63, so a bot that respawns underground with no pickaxe and no placeable blocks could never escape and held the child slot indefinitely (run K burned 23 minutes here after a single death). It now gives up after two minutes so bootstrap can try to gather wood and craft tools. Repeated S156 means the bot keeps dying underground - look at why it died, not at this code.";
            case "S157" -> "child swap throttle: ConstructNetherPortalBucketTask and HolePillarTask were replacing each other every tick (run L logged 4739 swaps and then went idle for 19.7 minutes), so neither ever made progress. stick() now holds whichever one currently owns the slot for three seconds before allowing the other to take over. Repeated S157 means the portal site is genuinely unusable - check that the bot has a bucket, water and a buildable spot, not this code.";
            case "S158" -> "shaft hopping: the bot pillared out of several DIFFERENT 1x1 shafts inside 90s. Every earlier guard was column-scoped (detectPingPong and noteChildFlip reset on any column change, stickyBlocked is exact equality), so a bot that digs a fresh shaft for each new iron target never tripped them - that is why E133 never fired and S147 has never appeared in any log. An area ban (radius, decaying) is now armed so the bot must relocate instead of digging the neighbouring shaft. Repeated S158 means iron is only reachable by shaft-digging; consider excluding steep/downward iron targets rather than loosening the ban.";
            case "S159" -> "spawn gate: the seed was rejected because it had no village and no ruined portal inside SpawnScout.SPAWN_LOOT_RADIUS, OR because it had a ruined portal but no wood nearby - the log line carries reason=no village/RP or reason=ruined portal but treeless, and those need different follow-ups. A village supplies wood (planks from buildings) so it is accepted alone; a bare ruined portal in a treeless biome is not playable: run P accepted SnowyTundraBiome rp=true rpDist=57, mined 8 iron, then could not craft the iron pickaxe for want of 2 sticks, wandered 160 blocks for logs and died (ph=BOOTSTRAP n=0 at 14:38). Run N burned the entire 38-minute budget in open water with 0 items and was scored 'playable' because the old test required the biome name to contain 'ocean' - a Forest or Plains spawn could never be rejected. The gate probes repeatedly up to 60s instead of checking once, because an unseen village is not an absent village, and stops rerolling after SpawnScout.MAX_REROLLS so a wrong check cannot burn the whole timeout. 'FORCED-ACCEPT' means the budget ran out - if you see that, the structure detection is too strict, not the seeds.";
            case "S160" -> "portal build timed out: one ConstructNetherPortalBucketTask instance owned the child slot for its whole budget without finishing, so the pin was suspended for 30s and the bot was sent wandering to relocate. stick() pins Construct deliberately so a half-built portal is never abandoned, but that pin had no exit - run O froze at 29,66,-84 with spd=0.000 for nine minutes (trace: zero swaps, one child for 300 consecutive ticks) waiting on iron for a second bucket it could never obtain. This is the 'child that can never finish' shape (same family as S156), so every ping-pong guard is blind to it - nothing ever swapped. Look at WHY the build cannot finish (missing resource? unreachable lava?) rather than raising the budget.";
            case "S161" -> "unrecoverable underground: the bot is below the surface with no pickaxe of any tier and nothing placeable, so it cannot break stone and cannot pillar - every action it can still take leads nowhere. Run Q reached PORTAL at 5:24 on the best seed of the session, died to a zombie at 9:34 in a shaft it had dug from y=71 to y=28, respawned into a 45-block pit at 119,19,202 with an empty inventory, and then logged S156 for seven straight minutes while holding the child slot. S156 used to claim it 'handed back to bootstrap' but never did: Task.tick() only swaps a child when !newSub.isEqual(sub), and isEqual answered 'any SurfaceBailTask', so the finished instance was ticked forever - the log shows the counter climbing 120s -> 371s. Two failed bails is now proof, and the seed is abandoned via ResetSignal. If you see S161, the fix is upstream: find why the bot died with its kit, not a way to dig stone with fists.";
            case "S162" -> "combat override: a hostile closed within 3.5 blocks while a pinned task owned the child slot, so the pin was broken to let AnyWeaponCombatTask run. stick() pins Construct/StepOffTable/SurfaceBail/wander deliberately so work is never abandoned mid-way, but those pins also swallowed the combat branch - run Q was being hit by a zombie at the bottom of its lava shaft and kept digging until it died. Bounded by where the driver asks for combat (closeHostile at 3.5 blocks, creeperInFace at 2.5), so this cannot fire spuriously. Repeated S162 in one place means the bot is standing in a spawn-dark cave, not that the override is wrong.";
            case "S163" -> "deep portal dig: ConstructNetherPortalBucketTask targets the nearest lava lake the block scanner has seen, and a deep lake means a 1x1 shaft straight down with no way back up. Run Q sank 175,187 from y=71 to y=28 (six fall-damage hits on the way), met a zombie at the bottom and lost the whole kit. Sinking below y=38 (S166 retune - it was y=30, which only fired below y=22 and missed run R entirely) in the dark for 15s with 4 more blocks lost is a failed dig: the cached portal site is cleared (isEqual keeps the same Construct instance alive, so without that the bot would pillar out and dig the identical shaft again) and HolePillarTask takes the slot. Repeated S163 means the scanner keeps choosing deep lava - prefer a surface or ravine lake instead of loosening the threshold.";
            case "S164" -> "child ping-pong, any pair: two children alternated six times inside one second, so neither could run, and the current one is now held for three seconds. S157 only ever knew about Construct <-> HolePillar, so run R's CraftInTableTask <-> GetOutOfWaterTask swapped 370 times in 16 seconds with no guard firing - the bot was standing in a river in a RiverBiome trying to craft at a table and GetOutOfWaterTask kept reclaiming the slot. Counted on the class pair, not on instances, because `wanted` is a new object every tick. Escape hatches (HolePillar, EnterNetherPortal, combat) are exempt: suppressing an escape turns oscillation into a stall, which is worse. If S164 fires on a pair you have fixed before, the pair-specific guard is not matching - check the class names in the message.";
            case "S165" -> "unrecoverable underground, fast proof: no pickaxe of any tier, nothing placeable, and either a 24-block drop within 10s of going underground or 30 straight seconds below y=45. Run R respawned at -136,63,-115 and fell to y=-1 in seventeen seconds, so it was dead in the void before SurfaceBailTask reached its 120s timeout - giveUps() stayed 0 and the give-up-based S161 could never fire. The two fast proofs are narrow on purpose: BOOTSTRAP legitimately spends time under a roof looking for iron, and a cave mouth walked down slowly can lose 24 blocks with nothing wrong, so the timeout proof also demands real depth and the fall proof also demands speed. S161 is the same dead end proven the slow way (a bail already gave up); the log line names which proof fired.";
            case "S165L" -> "lava lake choice: the portal build picked a lake below y=40, which forces a long dark shaft down to it. findLavaLake() now prefers the nearest lake at or above SAFE_LAKE_Y and only falls back to a deep one when there is no alternative, because run Q's deep lake is what dug the shaft it died in. Also fixes the pruning bug next door: `sqDist >= Math.max(nearestSqDistance, deepestFallbackSq)` skipped any candidate that could not beat BOTH trackers at once, so finding a surface lake pruned every deep fallback (and vice versa) - now it skips only when a candidate can beat neither.";
            case "S166" -> "shaft bleed: the portal build held the bot in the dark and it lost four hearts with no combat task taking the child slot, which means ranged damage. closeHostile() skips skeletons and witches on purpose - chasing ranged mobs burns the clock - so a bot being shot has nothing to fight and simply bleeds out. Run R: `Player29 was shot by Skeleton` at y=34, which is ABOVE S163's depth floor, so no depth-based guard was ever going to fire. Arms the same pillar-out bail as S163. One stray arrow is survivable and not worth abandoning a build for; four hearts is a fight the bot is losing.";
            case "S167" -> "spawn submerged in water: the S159 gate looks for a village or ruined portal and says nothing about the block the bot is standing in, so a water spawn sails through it. Run S spawned in a DesertLakes lake at -129,61,42, logged `spd=0.000` forever, and at t=1:15 a survival chain took the child slot and the driver never ticked again - the rest of the log is just `Refreshed inventory...` every 30s. Runs N (38 min, 0 items) and R (RiverBiome, 370 craft/water swaps) are the same shape. Eight continuous seconds submerged is the threshold: the bot swims across rivers all the time, so a single wet sample would reroll good seeds, but sustained submersion at spawn means escape-water pathing is not converging. If S167 fires on a seed you wanted, the fix is the water escape, not the threshold.";
            case "S168" -> "deadline starvation: two guards describe the same task and disagree about how long it gets. SurfaceBailTask.MAX_TICKS is 120s, but holdFor() fell through to the 40s default, so S140 replaced the bail every 40 seconds and the 120s give-up - which S156, the give-up cooldown, S161 and the whole unrecoverable chain all hang off - was UNREACHABLE. Run T sat at 29,31,-39 with sky=0, pick=0 and an empty inventory while S140 fired 14 times over five minutes and Baritone logged 'Failed exploring' every two seconds. Fixed twice over: holdFor now gives SurfaceBail/WaterBail 140s, and the bail itself gives up after 60s with zero vertical movement. The deadTicks counter is separate from noClimb because retarget() zeroes noClimb every 8s, so noClimb can never reach a 60s threshold - a counter that drives two decisions has to be two counters. If you see S168 again, look for another pair of constants that disagree about the same task's budget.";
            case "S169" -> "treeless spawn: the S159 gate accepted on STRUCTURE alone and SpawnScout's own resetWorthy flag was computed and then discarded by the accept branch. A ruined portal does not supply wood - only a village does, because its buildings are planks. Run P (SnowyTundraBiome, rp=true rpDist=57) mined 8 iron, could not craft the pickaxe for want of 2 sticks, wandered 160 blocks looking for logs and died at 14:38 with `ph=BOOTSTRAP n=0`; run U (BeachBiome, rp=true rpDist=33) logged `logs=0` in ALL 82 heartbeats across 24 minutes and sat at 180,61,-85 with `woodpick=0`. The old census was a 33x33 grid every 2 blocks, which misses a forest one hill away, so it is now 81x81 every 4. The census is one-sided on purpose - it exists to REJECT, never to vouch - so a zero count in a NON-treeless biome is treated as a scan failure (chunks not loaded yet) and does not throw the seed away on its own. If S169 keeps firing, check that the biome string in the log is actually in TREELESS_BIOMES before loosening anything: a false S169 costs a reroll, a missed one costs a whole run.";
            case "S170" -> "barren seed: the spawn gate runs exactly once, at t=20s, with only the spawn chunks loaded, so its verdict is a guess - and run U is what that guess cost (24 minutes, 0 logs, 0 items). This is the backstop that measures the thing that matters instead: if the gate has accepted and the bot still has ZERO logs eight minutes later while still in BOOTSTRAP, the seed has no usable wood and no amount of wandering will produce a pickaxe. It rerolls rather than spending the other 47 minutes of the harness budget. Tuned from the session: run T reached PORTAL at 4:07 and had sticks long before, and even a BOOTSTRAP that has to cross a river is done by ~5 minutes, so 8 is past every successful run and still only an eighth of the budget. Only fires on zero logs - a slow but working BOOTSTRAP is never touched.";
            case "S171" -> "hold inherited from the phase: holdFor() decides how long a child may sit on the same xz before S140 replaces it, and its branches are evaluated in order — so a branch added at the BOTTOM is unreachable for any phase matched above it. S168 added `if (child.contains(\"SurfaceBail\")) return 20*140;` after `if (\"PORTAL\".equals(phase)) return 20*90;`, so a surface bail running during PORTAL got 90s again, i.e. still less than SurfaceBailTask.MAX_TICKS (120s) — the very starvation S168 existed to fix, just relocated. The escape-task branch is now FIRST. Generalise: any `if` chain that dispatches on (phase, child) must test the most specific dimension first, and a child-specific budget must never be reachable-through a phase-specific one.";
            case "S172" -> "guard starvation by ORDERING, not by budget: the S165 unrecoverable check sat below the E90 'bootstrap in dark - surface' bail, and E90 ends in `return stick(new SurfaceBailTask())` on `phase == BOOTSTRAP && underground() && !cooling()` — a condition that is TRUE for precisely the bot S165 is written to catch (a respawn into a deep dark spot with an empty inventory). Run V respawned at 57,-2,225 with `sky=0 pick=0 iron=0 buck=0`, and E90 fired 20 times while S165 fired ZERO. Nothing was mis-tuned; the S165 block was simply below a `return` that always fired first. This is the same family as S168 (a timeout a shorter hold prevents you reaching) and S171 (a branch shadowed by an earlier branch in the same if-chain) — before trusting any guard, check what returns above it. Fixed by hoisting S165 above E90, plus a fourth fast proof `buriedAlive` (y<=0 && sky<=2 && unrecoverable) so the unmistakable case does not wait 30s for undergroundTicks. If S172 reappears, look for another early return between the top of the tick handler and your guard.";
            case "S173" -> "THE PILLARING BUG, located. `HolePillar.boxed()` is geometry-only ON PURPOSE (its comment: 'Geometry only. Sky light lies (caves, overhangs, night)') and that exclusion cannot tell 'trapped in a pit' from 'standing in the 1x1 ore shaft I just dug at the surface'. Run W: S130 fired 854 times, and ALL 18 START lines read `sky=15 boxed=true` at y=58-69. The loop is visible in the log — climb y=59 -> y=63 (S136 finishWhy=risen), walk back down to y=59 for the iron, get told 'boxed' again (S137 re-cool still-boxed@142,-178 walls=4/4/4), climb again — and at t=9:52 the bot still had `stonepick=0 iron=0` in a village spawn. Fix: `boxed()` now also requires that the column above is NOT open sky. A genuine pit has a roof and sky 0; a self-dug surface shaft has sky>=10 plus an unobstructed column, so requiring BOTH suppresses the false positive while keeping S130 armed for real pits. If S173 fires again, check the `sky=` value on the S130 line: sky 15 with boxed=true means this predicate is still too loose, and sky 0 means it is now too tight.";
            case "S174" -> "THE REROLL PATH HAS NEVER WORKED — and this is why resets look like harness faults. Every reset path (S159 reject, S167 water spawn, S165/S172 unrecoverable) fires ResetSignal -> AutoWorldState.rearm() -> mc.disconnect(), and the creation of the fresh world was driven by TitleScreen.tick(). disconnect() from a live integrated server does NOT land the headless client on TitleScreen, so the trigger never fired. Run W: a correct S165 reset at 23:35:27 logged `AUTOWORLD: re-armed for a fresh seed (reroll #1)` and then the client sat in the old world for 13+ minutes with a periodic `World save took 0ms` heartbeat, no title screen, no create call, silently until the harness timeout. It stayed hidden because the spawn gate is 7-for-7 and NO earlier run had ever needed a reroll, so the dead path cost nothing until the first time it was exercised. Fixed by driving creation from MinecraftClient.tick() (runs on every screen and in-world), keeping TitleScreen as the preferred path, and replacing the silent hang with a loud 45s give-up that names the stuck screen. If you see S174 again, check the `screen=` value in the give-up line: it tells you where the client is actually stuck.";
            case "S175" -> "THE CLIENT THREAD BLOCKED MID-TICK — and every existing guard was structurally blind to it. E199, S156, S160, S164, E98/E99 and the S152 marker are all evaluated FROM INSIDE THE TICK, so they can only ever observe a bot that is still ticking. Run X's trace.log is written by T2Trace on the client thread, once per tick, and it simply STOPS MID-FILE at t=8139 clk=7:06.7 — with the tick immediately before it covering 19.7 SECONDS of wall clock: `t=8128 clk=6:46.5 @-1.5,49.0,-77.6 g=true sel=6 child=HolePillarTask` then `t=8129 clk=7:06.2 @0.3,51.0,-79.1 g=true sel=7 child=HolePillarTask`. One tick, 19.7s, during which the bot moved 2 blocks and rose 2 y. The position then never changes again (`@0.3,51.0,-79.1` for the remaining 11 ticks) while the game log keeps printing 'Refreshed inventory...' and 'World save took 0ms' for another 22 minutes — the process is alive, the client thread is not ticking. The harness timeout 3300 was the only thing that ever ended it. IMPORTANT: the S152 `onStop interrupt=null` line and the PORTAL->FIGHT flapping that this session blamed first are SYMPTOMS of this stall, not its cause — do not chase the driver for this signature. Detection now runs on a daemon thread (T2Deadman), because a blocked thread cannot observe its own blockage: it measures wall-clock time against the driver's beat counter, reports any single tick over 8s as S176 the moment it happens, and hard-exits with code 87 after 120s of no progress so the harness does not burn the remaining timeout budget. If S175 fires, read trace.log's LAST 5 LINES — the gap between the final two MOVE timestamps is the stall duration, and the state on them (child, sel slot, y) is where the blocking call is.";
            case "S176" -> "a single client tick took longer than 8 seconds, reported at the moment it happened rather than only when it kills the run. Nothing in the project measured tick DURATION before this, so run X's 19.7-second tick was invisible when it occurred — its only trace was the gap between two adjacent lines of trace.log. A slow tick is a bug on its own (it desynchronises every wall-clock-based guard in T2Probe/T2Solve, which count TICKS and assume ~50ms each) even when the run survives it. This code ALSO fires for the second, independent failure: the client ticking normally while the speedrun driver is never reached, because it was latched stopped by `Task.stop(null)` (see S152 and SingleTaskChain.onStop/mainTask.stop()). The message says which: 'client is ticking but the speedrun driver has not been ticked for Ns' means the driver is latched, not that the client is blocked.";
            case "S177" -> "THE SEED WAS ACCEPTED ON A RUINED PORTAL AND THEN THE PORTAL WAS NEVER USED. The S159 spawn gate counts a ruined portal as a qualifying structure and reports `rp=true` with a `rpDist`, and every recent run has come in exactly that way — run T `village=false rp=true rpDist=64`, run U `rpDist=33`, run X `rpDist=63`. All three then built a portal the expensive way (water + lava bucket, or a full obsidian cast) while a usable frame sat inside 64 blocks, because `portal()` only ever asked `anyFound(Blocks.NETHER_PORTAL)` — a COMPLETED, LIT portal. A ruined portal is not that block: its frame is built from OBSIDIAN and CRYING_OBSIDIAN with a few blocks missing, so the check was a false negative every single time. This is the single largest overworld cost on the clock: it is why PORTAL->NETHER runs ~8 minutes (best ever 4:54) and why S165L deep-shaft fire-and-fallback fired 10 times in run X alone — the bot went digging for a lava lake it did not need. The fix is to treat the known frame as the preferred path: `ruinedPortal()` finds OBSIDIAN/CRYING_OBSIDIAN within 96 blocks, adopts it once (logging the site), and RuinedPortalFinishTask fills ONLY the missing frame blocks with cobblestone and lights it with flint and steel. No lava lake, no water bucket, no casting, no vertical travel. Give-up is bounded (2 attempts) so a frame that cannot be completed from the surface does not eat the run. If S177 fires, read the `adopting ruined portal @x,y,z dist=N` line that precedes it — if the frame is real and the bot still walked away, check that RuinedPortalFinishTask's orientation discovery found >= 3 obsidian on one axis, because a ruined portal generates on EITHER the X or Z axis and the frame cannot be assumed.";
            case "S177b" -> "THE RE-ADOPT LOOP — two constants describing the same trip disagreed. ruinedPortal() adopts a frame within 96 blocks; its first version ALSO revoked the site at >32 blocks ('walked far away; re-evaluate'). 32 < 96, so a frame adopted at dist=58 was dropped on the very next tick, the block scanner found the same obsidian, and the driver re-adopted it: `adopting ruined portal @135,10,153 dist=58` logged **22 times** ~4s apart for three straight minutes in run Z (7:17 → 8:08) while the bot never moved toward it. RuinedPortalFinishTask was constructed fresh 1215 times. Stickiness must not be distance-revocable — walking TO a site necessarily means being far from it. The site now clears only on a proven give-up. Generalise: whenever one guard says 'close enough to start' and another says 'too far, give up', the give-up threshold must be strictly LARGER or the pair oscillates; audit every pair of distance constants for this inversion. If S177b reappears, count `adopting ruined portal` lines — more than one per site means stickiness is being revoked again.";
            case "S178" -> "THE DESCENDING-SHAFT TRAP — the pillar ban was horizontal-only, so tunnelling straight down never cleared it. HolePillar's ban-clear test measured only |x-banX| + |z-banZ|. But the bot does not always leave a shaft sideways: while collecting iron it tunnels STRAIGHT DOWN. Run Z: S135 (S130 suppressed) fired 231 times with the bot descending a self-dug shaft inside one column — sky falling 9->7->6->3, place climbing 46->51 — and because manh stayed 0 the ban never cleared, so busy() stayed true and the pillar escape was suppressed the whole way down. stillBannedBoxed() meanwhile kept re-arming and DOUBLING the cool (lastCoolArmed*2, capped 20x20), which is how one column reached cool=197 ban=197. The same run then died in the mirror-image loop: E116 fired 55 times as an 8-block descending staircase (72->64->56->48->40->32->23) instead of a climb, E100 fired 222 times, and the final tick blocked 12.5s at HolePillarTask @144.7,45.0,125.5 with hp=10. Fix: the ban remembers banY and clears on EITHER a 2-block horizontal exit OR a 5-block vertical move — a depth change means different rock, different light, different escape geometry, so the decision must be re-made not inherited. Generalise: a 'has the player left the area?' test must measure every axis the player can leave by; a horizontal-only proximity test paired with a vertical escape route is a livelock by construction. If S178 recurs, check that the S138 clear line reports dy as well as manh.";
            case "S179" -> "THE TREE OSCILLATION — the bot moves back and forth over a tree instead of breaking it, and the anti-stall counter was structurally blind to it. Run AA: the bot walked to 43.7,-24.8, froze 152 ticks, then oscillated x=43.9 <-> 44.2 for 20+ seconds, never moving more than 1.1 blocks and never breaking the tree. The old guard bucketed position as `x >> 2` and required 160 ticks in one 4-block cell; the oscillation straddled the x=44 CELL BOUNDARY and crossed it 160 times between t=200 and t=700, resetting the counter every few ticks, so woodStill fired exactly ONCE in the entire run (t=171, during the initial freeze). Fix: a running BOUNDING BOX of positions, firing when the explored area stays <= 3 blocks in both axes after 8 seconds — a continuous measure with no boundary to straddle. The E97 line now reports the box and spans. Generalise: never measure 'has not moved' with a bucketed or discretised position; quantization introduces boundaries and the pathological case (jitter) is precisely the one that clusters at them. If S179 recurs, read the box= in the line — a small box with a large tick count is still the same failure.";
            case "S180" -> "THE DIG-DOWN / PILLAR-UP LIVELOCK — the pillar escape test was unsatisfiable, so the pillar always 'failed' and the bot re-entered the shaft it had just left. evaluateRise accepted a +4 rise outright, but for a marginal +2/+3 escape it required !boxed() && wallCount(feet-1) < 3 && headroom() && !columnUnderneath(). The last two are STRUCTURALLY IMPOSSIBLE for a bot that has just pillared out of a shaft: the shaft it climbed is always directly beneath it, and its walls are still there one level down, so a shallow escape could NEVER be confirmed. Run AB: the bot dug a 2-deep hole at the surface, S130 fired, it pillared 62->64, and its own tick log showed boxed=false walls=0/2/4 sky=11 — genuinely free, standing on the rim with open space all round. The strict test rejected it and logged `stuck-low ... roseReal=false giveUp=true`, arming a 12s ban; CollectIron then re-entered the same shaft. Measured: a clean 2-block oscillation, 4 pillar cycles in 103 seconds, iron never obtained. S141 (the reject log) never fired either, because riseStable was still 0 — the rejection was SILENT. Fix: clear = !boxed() && headroom() — an escape means the bot can move freely, which is exactly what boxed() tests. Leniency is the safe direction: a false accept costs one cool period (S130 re-fires), a false reject is a livelock. columnUnderneath() was deleted, not left unused, so nobody re-adds the call. Generalise: a conjunct that is always true in the exact situation it guards is not a guard but an unsatisfiable condition — ask of every conjunct 'could this ever be false here?', and log the REJECT, not just the accept. If S180 recurs, read the `marginal escape +Ny free` line and check `walls=` — wf=0 with a shaft beneath is the legitimate escape this now accepts.";
            case "S181" -> "THE STACK DUMP — making a blocked tick visible from outside. Runs AA, Z and AC all ended the same way: a single 30-40 SECOND tick inside MineAndCollectTask during BOOTSTRAP wood collection near spawn, then a permanent client-thread block. Run AC's was 40136ms, a new record worse than run X's 19.7s. It could never be diagnosed because every channel goes silent WITH the thread: the game log stops entirely (verified — zero non-bot lines across the whole stall window), and the tick's own trace line is lost too, because Runtime.halt() skips buffer flushing so the last buffered lines never reach disk. T2Deadman runs on its own daemon thread, so it calls clientThread.getStackTrace() WHILE the client is still stuck and names the exact frame; beat() captures the thread reference and the watchdog dumps once per stuck tick. Read the `at ...` frames below the S181 line — the topmost frame inside Baritone or Minecraft is where the 40 seconds went. Generalise: when a thread can hang, capture its identity early and let a DIFFERENT thread interrogate it. A hang that leaves no trace is not a mystery to reason about, it is a measurement you have not taken yet.";
            case "S182" -> "THE LOW-CEILING REJECT — the escape test demanded air 2 blocks above the head, which is false in every normal 2-high space. headroom() originally returned !solid(feet+2), 'not a ceiling lip'. But a 2-high tunnel or an overhang has feet and feet+1 free and feet+2 SOLID — a walkable ceiling, not a trap. So a bot that escaped into a normal low space was still rejected. Run AC's last stuck-low is the proof: `y=70 startY=68 walls=0/0/4 sky=12` — no walls at feet OR head, open sky, an unmistakably free bot, rejected purely because a block sat two above it. S180 had already accepted 7 other escapes in that same run; this was the one case its remaining conjunct still blocked. Fix: headroom() now checks feet+1 (the bot's own head block). !boxed() already establishes an opening at feet level, which is what 'can move' means. Generalise: when a predicate means 'is there room to stand', test the space the body actually occupies — testing one block beyond it silently excludes every tight-but-legal space (tunnels, doorways, under overhangs), which in a mining game is most of them.";
            case "S183" -> "THE BOBBING BOT — the water bail ended on an INSTANTANEOUS wet test, so a bot bobbing in water ended its own escape on every bob. isSubmergedInWater() is true only while the player's EYES are under water. A bobbing bot clears the surface for a tick at a time, so the first bob that lifted its eyes above the surface read as 'dry' and ended the bail — while the bot was still standing in the water. The parent resumed, the bot sank back in, S102 fired again, a fresh bail was built, and it ended on the next bob. Run AD (user-reported as 'the bot got stuck bobbing up and down in the water'): S102 every ~6s at spd=0.000 @243,61,136 for 30+ seconds, position never changing. Fix, two parts: (1) test ANY water contact from the WORLD (feet and head block fluid state) rather than eye submersion — the world cannot lie on a bob; (2) require 20 consecutive dry ticks before the bail may finish. Plus an escalation: after 5s with no horizontal progress, path to a visible shore, because a 1-deep pool has no swimmable exit and GetOutOfWaterTask can circle in it forever (findShore() already existed for this and had no caller). Generalise: an 'am I still in the bad state?' test must not use a quantity that OSCILLATES with the very behaviour being escaped — bobbing alternates the eyes above and below the surface, so an eye-based test is guaranteed to sample 'escaped' on some tick. Measure the stable thing (the water in the block) and require it to hold.";
            case "S184" -> "A FURNACE IS NOT A CRAFTING TABLE — the 'standing still means stuck' test was applied to a GUI where standing still is REQUIRED. T2Solve.workGui() lumps Furnace in with Craft/Inventory/Anvil/Chest, and the stall test that follows (flips >= 4 || sameXz > 4s || guiAge > 12s) is right for an instantaneous craft. Smelting one item takes 10 SECONDS and the bot must stand still with the screen open for it to finish, so the test closed the screen mid-smelt, the smelt aborted, the parent re-opened the furnace, and the cycle repeated. User-reported as 'the bot spins in circles when it is in the furnace ui'. Run AF: S120 craft-gui jump and E104 FurnaceScreen open 8s alternating every ~6s at @69,66,18 for the final minute, with E70 iron stall 6s alongside — the bot had the ore AND the furnace and still could not finish. Fix: slowGui() (Furnace, Brewing Stand) gets a long bounded budget (30s) and is NEVER closed by a same-xz test, because motionlessness is correct there. Generalise: a 'no progress' test is only valid against a proxy that actually tracks progress — standing still tracks 'stuck' for a craft and 'working correctly' for a furnace, so check whether the metric's SIGN flips between cases you are grouping together.";
            case "S185" -> "DETECT THE CONDITION, NOT THE NAME — the smelting stall guard keyed on the child task's NAME and therefore never applied. ModernSpeedrunTask.iron() suppressed the E70 stall ladder while smelting via `cn.contains(\"Smelt\") || cn.contains(\"Furnace\")`. But the child that actually drives smelting is CollectIronIngotTask — a name containing neither string. So `smelting` was FALSE exactly when smelting was happening, E70 was never suppressed, and it tore down and rebuilt the iron task every 6 seconds while the furnace ran. Run AG: `E104 FurnaceScreen open 8s` x11 and `E70 iron stall 6s` x9 interleaved at one spot, with CollectIronIngotTask logged as the child on every S120/S184 line. The guard's INTENT ('a furnace holds position by design') was correct; only its detection was wrong. Fix: slowScreenOpen() reads the live screen, which is the thing that actually means 'holding position is correct here'. Also stopped E104 counting a slow screen as a stall — it fired 11 false alarms on correct smelting behaviour. Generalise: a guard keyed on a task's class NAME breaks silently the moment a differently-named task performs the same work — names are a proxy for behaviour and proxies rot. Detect the condition itself (state, inventory, open screen) whenever one is available. Third instance in this project of a guard testing a proxy instead of the thing (see S173 'sky light lies' and S183 eye submersion).";
            case "S186" -> "RECOVER FROM A LATCHED DRIVER instead of halting a healthy run. T2Deadman.clientTickAlive() already detected the latch correctly — it counts client ticks with no matching driver beat and logs S176 after 30s — but it only REPORTED, and the watchdog then halted at 120s. Run AH is the proof: `S152 onStop interrupt=null dead=false ph=NETHER y=47.8` at 27:57.2, the driver never ticked again, and at 29:57 a run that had been working perfectly for 28 minutes was killed with code 87. S181 proved the latch is RECOVERABLE: its stack dump showed the client thread alive and rendering (glfwWaitEventsTimeout -> RenderSystem.limitDisplayFPS -> MinecraftClient.render), so world, player and inventory are all intact — only the task chain's main task was dropped. Re-installing it resumes the run, and because S152 keeps sessionLive set, onStart is swallowed by the E80 guard and the phase is NOT re-derived (no clock reset, no respawn into BOOTSTRAP). Bounded to 3 attempts: if re-installing does not take, this is not a latch and the fatal exit still fires. Generalise: when a detector already knows exactly what went wrong, check whether the condition is RECOVERABLE before wiring it to a kill — a watchdog that can only terminate converts a transient fault into a lost run. Reporting and recovering are different jobs.";
            case "S187" -> "walk nudge suppressed: every heading drops more than 3 blocks or meets lava within 4 blocks, so the blind turn-and-walk would have walked off a ledge (2026-09-24 02:32 NETHER y=95 death)";
            case "S188" -> "reroll disconnect: ResetSignal now leaves the world like Save-and-Quit (queued, world.disconnect first, then TitleScreen); before, disconnect() spun forever waiting for an integrated server nobody had told to stop";
            case "S189" -> "harness worlds were HARDCORE: AutoWorldCreateMixin passed true as LevelInfo arg 3 (yarn calls it structures; vanilla passes hardcore there). Deaths made the bot a spectator that sank through blocks - the respawn free-fall behind S165/S169/S172. Now hardcore=false";
            case "S190" -> "water bail kept: an unfinished WaterBailTask is no longer replaced by the phase task (was a per-tick CollectIron/CraftInTable<->WaterBail ping-pong, 63 incidents, one 396s craft stall)";
            case "S191" -> "nether climb-off-lava now targets y=52 (GetToYTask) instead of the exact block 12 overhead, which was usually netherrack (302s stall at 27,47,26)";
            case "S193" -> "nether climb stalled 30s with no height gain: climb abandoned for 60s and gold mined where the bot stands (climb otherwise continues from <48 up to 52)";
            case "S203" -> "child task flipped A<->B 4x in 60s: see faults.jsonl for the pair, add a latch or cooldown for it";
            case "S204" -> "crafting shield before the nether: MobDefenseChain blocks blaze fireballs with it";
            case "S202" -> "nether climb restarted 3x in 60s (gold dig keeps dropping below 48): climb off for 90s, gold mined in place";
            case "S194" -> "dig-down in progress: a collector is mining straight down (Y fell in the last 3s), so pillar-out/jump nudges stand aside instead of pillaring back up with the cobble it just mined";
            case "E109b", "S109" -> "mining with a block in hand: force-equip the pick (S109 does this)";
            case "S130", "S131", "S132", "S133", "S134", "S135", "S136", "S137", "S138" ->
                    "pillar state machine: check ban column vs actual shaft column";
            default -> "see T2Codes / paste faults.log";
        };
    }
}
